  - name: Install yum
    yum:
      name:
        - wget
        - java-1.8.0-openjdk
        - git

  - name: Download jenkins.repo
    get_url:
      url: https://pkg.jenkins.io/redhat/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import Jenkins Key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: Install Jenkins
    yum:
      name: jenkins
      state: present

  - name: Start & Enable Jenkins
    systemd:
      name: jenkins
      state: started
      enabled: true

  - name: Open Firewall Port
    firewalld:
      zone: public
      port: 8080/tcp
      permanent: true
      state: enabled
      immediate: true

  - name: Sleep for 40 seconds and continue with play
    wait_for: timeout=40

  - name: read admin pwd
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: adminpwd

  - name: unlock and add admin user
    jenkins_script:
     script: |
      import jenkins.model.*
      import hudson.security.*
      def instance = Jenkins.getInstance()
      def hudsonRealm = new HudsonPrivateSecurityRealm(false)
      hudsonRealm.createAccount('jenkins', '${user_pwd}')
      instance.setSecurityRealm(hudsonRealm)
      def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
      strategy.setAllowAnonymousRead(false)
      instance.setAuthorizationStrategy(strategy)
      instance.save()
     args:
      user_pwd: "{{ admin_user_pass }}"
     user: admin
     password: "{{ adminpwd.stdout  }}"

  - name: complete setup wizard
    jenkins_script:
     script: |
      import static jenkins.model.Jenkins.instance as jenkins
      import jenkins.install.InstallState
      if (!jenkins.installState.isSetupComplete()) {
        InstallState.INITIAL_SETUP_COMPLETED.initializeState()
      }
     user: admin
     password: "{{ adminpwd.stdout }}"

